### ISSUE TITLE
Incompatible with my Linksys WRT-54G

### ISSUE THREAD

**Issue by mohitsud** [superloopnetwork/superloop#2]
I have run the audit creeper command on my system but I do not see the expected results. The exact command I am running is:

`superloop.py host exec "show ip int br" -n core.*sw   | AWKward linksys-wrt54g             `

After running this on my system, I get an error stating "INSUFFICIENT MEMORY". I think it has to do with the zombie processes and semaphores. 

I am running an 486 with a Linksys WRT-54G router. I also have a set of LabTec speakers that are used with my OS of Windows Media Center edition installed which is by the far the best PVR I have ever used.

**Comment by superloopnetwork** [comment]
In order to execute 'superloop' as a command itself, you will need to place the superloop.py file in your $PATH directory. Do a ```echo $PATH``` to check. I placed mine in ```/usr/local/bin```. Follow lines 13-40 in the README.md file. This will help you out.

I don't think ```superloop``` will support WRT54G platform or will it ever. I do love those LabTec speakers though! And yes, you're right - hands down, Windows Media Center Edition is by far the bet PVR experience I had as well. *like*
