### ISSUE TITLE
Let's close the loop 

### ISSUE THREAD

**Issue by mohitsud** [superloopnetwork/superloop#5]
I am a bit confused by the name of your product. Why is it called superloop? If you found a way to update the configs on multiple networking appliances why not call it super config or aftershocks?

**Comment by superloopnetwork** [comment]
Good question... So not only is 'superloop' able to push out configs simultaneously to one or infinite amount of nodes, but it's able to do more than that like auditing, rendering, remediation, etc... 'superloop' was derived because I had networks around the world... San Jose, Kitchener, Woodstock... And they were all interconnected... Hence the name 'superloop'.
